name: phynteny
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>3.7,<3.11
  - biopython>=1.79
  - click
  - pandas
  - numpy
  - loguru
  - joblib
  - pickle5
  - scikit-learn<=1.2.2
  - tensorflow==2.9.1
