name: phynteny_test5
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>=3.8,<3.11
  - biopython
  - pickle5
  - click
  - pandas
  - numpy
  - loguru
  - joblib
  - scikit-learn
  - pip
  - pip:
      - tensorflow==2.9.1
