name: phynteny
channels:
  - anaconda
  - defaults
dependencies:
  - python>=3.7
  - biopython>=1.79
  - pickle5
  - click
  - pandas 
  - numpy==1.24
  - loguru
  - joblib
  - scikit-learn==1.2.2
  - tensorflow==2.9.0
