name: phynteny_test2
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>3.7,<3.11
  - biopython>=1.79
  - pickle5
  - click
  - pandas
  - numpy
  - loguru
  - joblib
  - scikit-learn<=1.2.2
  - pip
  - pip:
      - tensorflow==2.9.1
