# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10"]

    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      # Setup env
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: phynteny
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: "Setup Phables on ${{ matrix.os }} for Python ${{ matrix.python-version }}"
        run: |
          python -m pip install --upgrade pip
          pip install .
      
      - name: "Generate coverage report on ${{ matrix.os }} for Python ${{ matrix.python-version }}"
        run: |
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report xml --cov-report lcov --cov-append
